alias src="source ~/.bashrc"
alias reload="source ~/.bashrc"
alias cat="bat"
alias cd="z"
alias ll='ls -l'
alias la='ls -Al'
alias lt='ls -ltrh'
alias bashrc="micro ~/.bashrc"
alias aliases="micro ~/.bash_aliases"
alias ls="eza"
alias home="z /c/Users/Arthur"
